import ProjectCard from "./ProjectCard";

function ProjectCarousel() {
  return (
    <div className="carousel w-full">
      <div id="slide1" className="carousel-item relative w-full">
        <ProjectCard
          title="Portfolio Website"
          description="Welcome to my portfolio — a place where I share the projects I’ve built and the things I’ve learned along the way."
          technologies={["React", "TailwindCSS", "DaisyUI"]}
          url=""
        />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide3" className="btn btn-circle">❮</a>
          <a href="#slide2" className="btn btn-circle">❯</a>
        </div>
      </div>

      <div id="slide2" className="carousel-item relative w-full">
        <ProjectCard
          title="Foodplanner"
          description="A learning project to track your fridge contents and discover recipes generated by AI from the ingredients you already have."
           technologies={["React Native", "Expo", "React Native Paper"]}
           url=""
        />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide1" className="btn btn-circle">❮</a>
          <a href="#slide3" className="btn btn-circle">❯</a>
        </div>
      </div>

      <div id="slide3" className="carousel-item relative w-full">
        <ProjectCard
          title="IHK Project Proposals"
          description="A team project developed by three people for managing and reviewing IHK project submissions."
          technologies={["React", "Next.js", "MaterialUI"]}
        />
        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <a href="#slide2" className="btn btn-circle">❮</a>
          <a href="#slide1" className="btn btn-circle">❯</a>
        </div>
      </div>
    </div>
  );
}

export default ProjectCarousel;
