import { useState } from "react";
import ProjectCard from "./ProjectCard";
import { useEffect } from "react";

const projects = [
  <ProjectCard
    title="Portfolio Website"
    description="Welcome to my portfolio — a place where I share the projects I’ve built and the things I’ve learned along the way."
    technologies={["React", "TailwindCSS", "DaisyUI"]}
    url=""
  />,
  <ProjectCard
    title="Foodplanner"
    description="A learning project to track your fridge contents and discover recipes generated by AI from the ingredients you already have."
    technologies={["React Native", "Expo", "React Native Paper"]}
    url=""
  />,
  <ProjectCard
    title="IHK Project Proposals"
    description="A team project developed by three people for managing and reviewing IHK project submissions."
    technologies={["React", "Next.js", "MaterialUI"]}
  />,
];

function App() {
  const [currentSlide, setCurrentSlide] = useState(0);

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev === 0 ? projects.length - 1 : prev - 1));
  };

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev === projects.length - 1 ? 0 : prev + 1));
  };

  useEffect(() => {
    const interval = setInterval(() => {
      nextSlide();
    }, 8000); // alle 5 Sekunden

    return () => clearInterval(interval);
  }, []);

  return (
    <>
    
      <div className="relative basis-8/12 overflow-hidden rounded-xl mt-30">
        <div className="text-3xl font-bold mb-4">Projects</div>
        <div
          className="flex transition-transform duration-500 ease-in-out"
          style={{
            transform: `translateX(-${currentSlide * 100}%)`,
            willChange: "transform",
          }}
        >
          {projects.map((img, index) => (
            <div className="min-w-full" key={index}>
              {img}
            </div>
          ))}
        </div>

        <div className="absolute left-5 right-5 top-1/2 flex -translate-y-1/2 transform justify-between">
          <button onClick={prevSlide} className="btn btn-circle">
            ❮
          </button>
          <button onClick={nextSlide} className="btn btn-circle">
            ❯
          </button>
        </div>

        <div className="absolute bottom-4 left-0 right-0 flex justify-center gap-2">
          {projects.map((_, index) => (
            <button
              key={index}
              onClick={() => setCurrentSlide(index)}
              className={`w-3 h-3 rounded-full transition-colors duration-300 ${
                index === currentSlide ? "bg-indigo-700" : "bg-gray-300"
              }`}
            />
          ))}
        </div>
      </div>
     
    </>
  );
}

export default App;
