import { useState } from "react";
import ProjectCard from "./ProjectCard";
import { useEffect } from "react";

const projects = [
  <ProjectCard
    title="Portfolio Website"
    description="Welcome to my portfolio — a place where I share the projects I’ve built and the things I’ve learned along the way."
    technologies={["React", "TailwindCSS", "DaisyUI"]}
    url="https://github.com/sfronauer/WebPortfolio"
    picture="portfolio.png"
  />,
  <ProjectCard
    title="Foodplanner"
    description="A learning project to track your fridge contents and discover recipes generated by AI from the ingredients you already have."
    technologies={["React Native", "Expo", "React Native Paper"]}
    url="https://github.com/sfronauer/Essensplaner"
    picture="foodplanner.png"
  />,
  <ProjectCard
    title="IHK-Project-Proposals"
    description="A team project developed by three people for managing and reviewing IHK project submissions."
    technologies={["React", "Next.js", "MaterialUI"]}
    url="https://github.com/sfronauer/IHK_Projektantraege"
    picture="ihk.png"
  />,
  <ProjectCard
    title="Tamagotchi"
    description="A digital pet where you feed, play with, and care for a pixel-art cat."
    technologies={["Arduino", "C/C++"]}
    url="https://github.com/sfronauer/Tamagotchi"
    picture="tamagotchi.png"
  />,
];

function App() {
  const [currentSlide, setCurrentSlide] = useState(0);

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev === 0 ? projects.length - 1 : prev - 1));
  };

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev === projects.length - 1 ? 0 : prev + 1));
  };

  useEffect(() => {
    const interval = setInterval(() => {
      nextSlide();
    }, 10000);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <div className="text-3xl font-bold mt-30 mb-5">Projects</div>

      <div className="relative w-full overflow-hidden rounded-2xl shadow-lg shadow-primary/20 hover:scale-105 transition-transform duration-300 ease-out">
        <div
          className="flex transition-transform duration-500 ease-in-out"
          style={{ transform: `translateX(-${currentSlide * 100}%)` }}
        >
          {projects.map((p, index) => (
            <div className="min-w-full flex justify-center" key={index}>
              {p}
            </div>
          ))}
        </div>

        <div className="absolute left-2 right-2 top-1/2 flex justify-between -translate-y-1/2">
          <button
            onClick={prevSlide}
            className="btn btn-circle btn-sm border-amber-50"
          >
            ❮
          </button>
          <button
            onClick={nextSlide}
            className="btn btn-circle btn-sm border-amber-50"
          >
            ❯
          </button>
        </div>

        <div className="absolute bottom-2 left-0 right-0 flex justify-center gap-2">
          {projects.map((_, index) => (
            <button
              key={index}
              onClick={() => setCurrentSlide(index)}
              className={`w-2 h-2 rounded-full transition-colors duration-300 ${
                index === currentSlide ? "bg-indigo-700" : "bg-gray-300"
              }`}
            />
          ))}
        </div>
      </div>
    </>
  );
}

export default App;
